const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$("#starCanvas"),ctx=canvas.getContext("2d");
const pages={menu:$("#menuPage"),mode:$("#modePage"),practice:$("#practicePage")};
const title=$("#selectedStarTitle"),practiceTitle=$("#practiceTitle"),instruction=$("#instruction"),modeLabel=$("#modeLabel"),celebration=$("#clearCelebration"),replay=$("#replayButton"),undo=$("#undoButton"),reset=$("#resetButton"),speedControls=$("#speedControls"),secret=$("#secretStarButton");
const CFG={5:{step:2},7:{step:3},8:{step:3},10:{step:3},12:{step:5},16:{step:7}};
const LABEL={5:"5芒星",7:"7芒星",8:"8芒星",10:"10芒星",12:"12芒星",16:"ひみつの16芒星"};
const STORE="kids-star-app-cleared-v2",C={x:300,y:300},R=218,DOT=16,HIT=43;
let star=5,mode="watch",pts=[],sequence=[],edges=[],wrongEdges=[],drawing=null,index=0,raf=null,speed="normal",complete=false,startDot=null;
const modes={watch:["書き方を見る","くろい せんが うごくよ。じゅんばんを よく みてね。"],trace:["なぞって書く","うすい おてほんの せんを、ひかる てんから なぞろう。"],try:["自分で一筆書き","どの てんからでも いいよ。ゆびを はなさず さいごまで！"]};
function page(name){Object.entries(pages).forEach(([k,v])=>v.hidden=k!==name);scrollTo({top:0,behavior:"smooth"})}
function cleared(){try{return new Set(JSON.parse(localStorage.getItem(STORE)||"[]").map(String))}catch{return new Set}}
function save(){const s=cleared();s.add(String(star));localStorage.setItem(STORE,JSON.stringify([...s]));refreshProgress()}
function refreshProgress(){const s=cleared();$$('[data-clear-for]').forEach(b=>b.hidden=!s.has(b.dataset.clearFor));const open=s.has("12");secret.disabled=!open;secret.classList.toggle("locked",!open);secret.querySelector(".lock-mark").textContent=open?"✨":"🔒";drawPreviews()}
function makeSequence(n,start=0){const a=[start],step=CFG[n].step;let p=start;for(let i=0;i<n;i++){p=(p+step)%n;a.push(p)}return a}
function makePoints(n,r=R,c=C){return Array.from({length:n},(_,i)=>{const a=-Math.PI/2+i*Math.PI*2/n;return{x:c.x+Math.cos(a)*r,y:c.y+Math.sin(a)*r}})}
function drawPreviews(){$$(".star-preview").forEach(c=>{const n=+c.dataset.preview,p=makePoints(n,58,{x:75,y:75}),seq=makeSequence(n),x=c.getContext("2d"),locked=n===16&&!cleared().has("12");x.clearRect(0,0,150,150);x.beginPath();x.moveTo(p[seq[0]].x,p[seq[0]].y);seq.slice(1).forEach(i=>x.lineTo(p[i].x,p[i].y));x.strokeStyle=locked?"#8e8e8e":"#f0ad20";x.lineWidth=6;x.lineJoin=x.lineCap="round";x.stroke()})}
function selectStar(n){if(n===16&&secret.disabled)return;star=n;title.textContent=LABEL[n];page("mode")}
function startMode(m){mode=m;practiceTitle.textContent=LABEL[star];modeLabel.textContent=modes[m][0];instruction.textContent=modes[m][1];speedControls.hidden=m!=="watch";replay.hidden=m!=="watch";undo.hidden=m==="watch";reset.hidden=m==="watch";page("practice");restart()}
function restart(){cancelAnimationFrame(raf);edges=[];wrongEdges=[];drawing=null;index=0;startDot=null;complete=false;celebration.hidden=true;pts=makePoints(star);sequence=makeSequence(star);render();if(mode==="watch")animateGuide()}
function animateGuide(){cancelAnimationFrame(raf);edges=[];let seg=0,start=performance.now();const tick=now=>{const duration=speed==="slow"?900:480,progress=Math.min((now-start)/duration,1);render({seg,progress});if(progress===1){edges.push([sequence[seg],sequence[seg+1]]);seg++;start=now;if(seg>=sequence.length-1){render();instruction.textContent="さいごまで みられたね！";return}}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)}
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*600/r.width,y:(e.clientY-r.top)*600/r.height}}
function near(q,candidates){let hit=null,b=HIT;candidates.forEach(i=>{const d=Math.hypot(q.x-pts[i].x,q.y-pts[i].y);if(d<=b){b=d;hit=i}});return hit}
function drawGuideShape(){if(mode!=="trace")return;ctx.save();ctx.beginPath();ctx.moveTo(pts[sequence[0]].x,pts[sequence[0]].y);sequence.slice(1).forEach(i=>ctx.lineTo(pts[i].x,pts[i].y));ctx.strokeStyle="rgba(38,52,59,.26)";ctx.lineWidth=8;ctx.lineCap=ctx.lineJoin="round";ctx.stroke();ctx.restore()}
function render(anim=null){ctx.clearRect(0,0,600,600);ctx.fillStyle="#fff";ctx.fillRect(0,0,600,600);ctx.save();ctx.beginPath();ctx.arc(300,300,R,0,Math.PI*2);ctx.setLineDash([8,11]);ctx.strokeStyle="rgba(81,139,158,.2)";ctx.lineWidth=4;ctx.stroke();ctx.restore();drawGuideShape();drawEdges(edges,"#4ca9d2",11);drawEdges(wrongEdges,"#e86d6d",9);if(anim){const a=pts[sequence[anim.seg]],b=pts[sequence[anim.seg+1]],x=a.x+(b.x-a.x)*anim.progress,y=a.y+(b.y-a.y)*anim.progress;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(x,y);ctx.strokeStyle="#26343b";ctx.lineWidth=10;ctx.lineCap="round";ctx.stroke()}
 if(drawing){ctx.beginPath();ctx.moveTo(pts[drawing.from].x,pts[drawing.from].y);drawing.path.forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle="#ec78ad";ctx.lineWidth=9;ctx.lineCap=ctx.lineJoin="round";ctx.stroke()}
 if(!complete){let active=[];if(mode==="trace")active=[sequence[index],sequence[index+1]].filter(Number.isInteger);pts.forEach((p,i)=>{const on=active.includes(i);ctx.beginPath();ctx.arc(p.x,p.y,on?DOT+5:DOT,0,Math.PI*2);ctx.fillStyle=on?"#ffcc3f":"#fff";ctx.strokeStyle=on?"#e99b22":"#5bb4c9";ctx.lineWidth=on?5:4;if(on){ctx.shadowColor="rgba(255,187,48,.7)";ctx.shadowBlur=16}else ctx.shadowBlur=0;ctx.fill();ctx.stroke()});ctx.shadowBlur=0}}
function drawEdges(list,color,width){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap=ctx.lineJoin="round";list.forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(pts[a].x,pts[a].y);ctx.lineTo(pts[b].x,pts[b].y);ctx.stroke()});ctx.restore()}
function down(e){if(mode==="watch"||complete)return;const q=pos(e);let hit=null;
 if(mode==="trace"){const need=sequence[index];hit=near(q,[need]);if(hit===null){instruction.textContent=index?"ひかっている てんから つづけてね。":"ひかっている さいしょの てんから はじめてね。";return}}
 else{if(index===0){hit=near(q,pts.map((_,i)=>i));if(hit===null){instruction.textContent="すきな てんの うえから はじめてね。";return}startDot=hit;sequence=makeSequence(star,startDot)}else{hit=near(q,[sequence[index]]);if(hit===null){instruction.textContent="いまの てんから つづけてね。";return}}}
 e.preventDefault();canvas.setPointerCapture(e.pointerId);drawing={from:hit,path:[pts[hit]],pointer:e.pointerId,lastWrong:null};render()}
function move(e){if(!drawing||drawing.pointer!==e.pointerId)return;e.preventDefault();const q=pos(e);drawing.path.push(q);const target=sequence[index+1];if(Number.isInteger(target)&&near(q,[target])!==null){edges.push([sequence[index],target]);index++;drawing.from=target;drawing.path=[pts[target]];drawing.lastWrong=null;if(index===sequence.length-1){finish(mode==="try");return}render();return}const others=pts.map((_,i)=>i).filter(i=>i!==drawing.from&&i!==target),bad=near(q,others);if(bad!==null&&drawing.lastWrong!==bad){wrongEdges.push([drawing.from,bad]);drawing.lastWrong=bad;instruction.textContent="その せんだけ あかくしたよ。『ひとつもどる』で けせるよ。"}render()}
function up(e){if(!drawing||drawing.pointer!==e.pointerId)return;drawing=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(index<sequence.length-1){if(mode==="try"){instruction.textContent="ゆびを はなさず、さいごまで かいてみよう！";edges=[];wrongEdges=[];index=0;startDot=null;sequence=makeSequence(star)}else{instruction.textContent="せんは のこっているよ。ひかる てんから つづけよう。"}}render()}
function finish(self){drawing=null;complete=true;render();if(mode==="try"&&self&&wrongEdges.length===0){save();celebration.hidden=false;instruction.textContent="じぶんの ちからで できたね！"}else{instruction.textContent="なぞった せんが きれいに のこったね！"}}
canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);
undo.addEventListener("click",()=>{if(wrongEdges.length){wrongEdges.pop();instruction.textContent="まちがえた せんを ひとつ けしたよ。"}else if(edges.length){edges.pop();index=Math.max(0,index-1);complete=false;celebration.hidden=true}render()});reset.addEventListener("click",restart);replay.addEventListener("click",restart);
$$('[data-speed]').forEach(b=>b.addEventListener("click",()=>{speed=b.dataset.speed;$$('[data-speed]').forEach(x=>x.classList.toggle("selected",x===b));restart()}));
$$('[data-star]').forEach(b=>b.addEventListener("click",()=>selectStar(+b.dataset.star)));$$('[data-mode]').forEach(b=>b.addEventListener("click",()=>startMode(b.dataset.mode)));
$("#modeBackButton").addEventListener("click",()=>page("menu"));$("#practiceBackButton").addEventListener("click",()=>{cancelAnimationFrame(raf);page("mode")});
refreshProgress();render();